### PR TITLE
Handle filenames with leading periods correctly

### LINKED ISSUE #49: isCrossedBoundary incorrectly identifies path "..foo" as cross boundary
If there is a file named `..foo`, `isCrossedBoundary` returns true, when it should not. (Disregarding the terrible naming of said file)

### PR DESCRIPTION
**Pull request by whickman**
Fixes #49 
Test function name is questionable, happy to change

### CODE REVIEW

**Comment by whickman** [comment]
tests were passing locally, but if this actually breaks the functionality I'm happy to close

File: helper/chroot/chroot.go [hunk 1]
```diff
@@ -37,7 +37,7 @@ func isCrossBoundaries(path string) bool {
 	path = filepath.ToSlash(path)
 	path = filepath.Clean(path)
 
-	return strings.HasPrefix(path, "..")
+	return strings.HasPrefix(path, "../") || strings.HasPrefix(path, "..\\")
```
Comment (orirawlings) [inline helper/chroot/chroot.go]: Maybe:

```
strings.HasPrefix(path, ".." + filepath.Separator)
```
