### PR TITLE
 util.TempFile: use ioutil-like implementation, fixes #41

### LINKED ISSUE #41: there is a maximum global temp file limit on util and memfs
There is currently a global temp file limit on `util.TempFile`:
https://github.com/src-d/go-billy/blob/c329b7bc7b9d24905d2bc1b85bfa29f7ae266314/util/util.go#L134

This is then used by `memfs` as well as third party code to get temp files.

There should not be a limit of total temporary files. Not global and not per-filesystem. It's very easy to exhaust this maximum on any long-running application. If any, there could be a limit of open files _at the same time_ (as with Linux limits).

The issue can be reproduced adding the following test to `test/tempfile.go`:

```go
func (s *TempFileSuite) TestTempFileMany(c *C) {
	for i := 0; i < 1024; i++ {
		var fs []billy.File

		for j := 0; j < 100; j++ {
			f, err := s.FS.TempFile("test-dir", "test-prefix")
			c.Assert(err, IsNil)
			fs = append(fs, f)
		}

		for _, f := range fs {
			c.Assert(f.Close(), IsNil)
			c.Assert(s.FS.Remove(f.Name()), IsNil)
		}
	}
}
```

Then test output is as follows:

```
$ go test ./...
?   	gopkg.in/src-d/go-billy.v3	[no test files]
# gopkg.in/src-d/go-billy.v3/util
util/util_test.go:10: assert declared and not used
ok  	gopkg.in/src-d/go-billy.v3/helper/chroot	0.010s
ok  	gopkg.in/src-d/go-billy.v3/helper/mount	0.005s
ok  	gopkg.in/src-d/go-billy.v3/helper/polyfill	0.006s

----------------------------------------------------------------------
FAIL: <autogenerated>:40: TemporalSuite.TestTempFileMany

/home/smola/dev/go/src/gopkg.in/src-d/go-billy.v3/test/tempfile.go:59:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"max. number of tempfiles reached"} ("max. number of tempfiles reached")


----------------------------------------------------------------------
FAIL: <autogenerated>:41: TemporalSuite.TestTempFileWithPath

/home/smola/dev/go/src/gopkg.in/src-d/go-billy.v3/test/tempfile.go:29:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"max. number of tempfiles reached"} ("max. number of tempfiles reached")

OOPS: 4 passed, 2 FAILED
--- FAIL: Test (0.04s)
FAIL
FAIL	gopkg.in/src-d/go-billy.v3/helper/temporal	0.046s

----------------------------------------------------------------------
FAIL: <autogenerated>:122: MemorySuite.TestTempFileMany

/home/smola/dev/go/src/gopkg.in/src-d/go-billy.v3/test/tempfile.go:59:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"max. number of tempfiles reached"} ("max. number of tempfiles reached")


----------------------------------------------------------------------
FAIL: <autogenerated>:123: MemorySuite.TestTempFileWithPath

/home/smola/dev/go/src/gopkg.in/src-d/go-billy.v3/test/tempfile.go:29:
    c.Assert(err, IsNil)
... value *errors.errorString = &errors.errorString{s:"max. number of tempfiles reached"} ("max. number of tempfiles reached")

OOPS: 90 passed, 2 FAILED
--- FAIL: Test (0.04s)
FAIL
FAIL	gopkg.in/src-d/go-billy.v3/memfs	0.046s
ok  	gopkg.in/src-d/go-billy.v3/osfs	1.508s
?   	gopkg.in/src-d/go-billy.v3/test	[no test files]
FAIL	gopkg.in/src-d/go-billy.v3/util [build failed]
```

### PR DESCRIPTION
**Pull request by smola**
* Adapt iotuil.TempFile to billy.
* This prevents having a global temporary file maximum.
* Also prevents race-condition on getting the file name.
* helper/temporal: run full filesystem test suite
* test: test that we can open a lot of temp files

### CODE REVIEW

File: util/util.go [hunk 1]
```diff
@@ -114,38 +114,60 @@ func WriteFile(fs billy.Basic, filename string, data []byte, perm os.FileMode) e
...
+	rand = r
+	randmu.Unlock()
+	return strconv.Itoa(int(1e9 + r%1e9))[1:]
 }
 
-func getTempFilename(fs billy.Basic, dir, prefix string) string {
-	atomic.AddInt32(&tempCount, 1)
-	filename := fmt.Sprintf("%s_%d_%d", prefix, tempCount, time.Now().UnixNano())
-	return fs.Join(dir, filename)
+// TempFile creates a new temporary file in the directory dir
```
Comment (mcuadros) [inline util/util.go]: comments  80 chars width

Comment (smola) [inline util/util.go]: :+1: it was like that in Go stdlib. Reformatted.

**Comment by alcortesm** [comment]
I think you might be referring to another repository when you say in the title of this PR and on the commit messages that this PR fixes #22.

**Comment by smola** [comment]
@alcortesm Wrong number, it's #41
